#!/bin/sh 

# iAnywhere Solutions, Inc. One Sybase Drive, Dublin, CA 94568, USA
# Copyright (c) 2001-2008, iAnywhere Solutions, Inc. Portions copyright (c)
# 1988-2008, Sybase, Inc. All rights preserved. All unpublished rights reserved.

svc_t_init()
############
{
    NOOP=NOOP
}

svc_t_toolname()
################
{
    echo "rshost"
}

svc_t_toolspath()
#################
# can look at $BITNESS, $BIN32, etc. here to override bitness
# 's' path is the script or shortcut path for this tool
{
    echo $SQLANYDIR/${BIN}s/`svc_t_toolname`
}

svc_t_toolpath()
################
# can look at $BITNESS, $BIN32, etc. here to override bitness
{
    echo $SQLANYDIR/$BIN/`svc_t_toolname`
}

svc_t_has_servername()
################
{
    false
}

svc_t_need_servername()
#################
{
    false
}

svc_t_process_cmdline()
#######################
# in: cmdline
# out: add -ud if not already there
{
    local MY_CMDLINE=`svc_t_process_cmdline_add_ud $*`

    echo "$MY_CMDLINE"
}

